name: pytest

on:
  push:
    tags: 'v*'

jobs:
  ci:
    runs-on: ubuntu-latest
    name: manylinux-deploy
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      name: Setup Python
      with:
        python-version: 3.9
    - name: Build manylinux
      uses: RalfG/python-wheels-manylinux-build@v0.6.0-manylinux2014_x86_64
      with:
        python-versions: 'cp39-cp39 cp310-cp310'
        system-packages: 'llvm clang cmake python3 python3-pip llvm-toolset-7-clang-tools-extra'
        pre-build-command: 'python3 -mpip install conan twine'
    - name: Publish wheels to PyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        twine upload dist/*manylinux*
