name: pytest

on:
  push:
    tags: 'v*'

jobs:
  ci:
    runs-on: ubuntu-latest
    name: manylinux-deploy
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      name: Setup Python
      with:
        python-version: 3.9
    - name: Build manylinux
      uses: RalfG/python-wheels-manylinux-build@v0.6.0-manylinux2014_x86_64
      with:
        python-versions: 'cp39-cp39 cp310-cp310'
        system-packages: 'llvm clang cmake'
        pre-build-command: 'python -mpip install conan'
    - uses: pypa/gh-action-pypi-publish@release/v1
      with:
        skip_existing: true
        password: ${{ secrets.PYPI_API_TOKEN }}

