name: pytest

on:
  push:
    tags: 'v*'

jobs:
  ci:
    runs-on: ${{ matrix.info.os }}
    strategy:
      matrix:
        info:
          - os: windows-latest
            python: "3.9"
          - os: windows-latest
            python: "3.10"
          - os: macos-10.15
            python: "3.9"
          - os: macos-latest
            python: "3.10"
    name: ${{matrix.info.os}} ${{ matrix.info.python }}
    steps:
    - uses: actions/checkout@v2
    - uses: lukka/get-cmake@latest
    - uses: actions/setup-python@v2
      name: Setup Python ${{ matrix.info.python }}
      with:
        python-version: ${{ matrix.info.python }}
    - name: Deps
      run: |
        python -m pip install --upgrade pip
        make requirements
    - name: Build
      run: |
        python setup.py bdist_wheel
    - uses: pypa/gh-action-pypi-publish@release/v1
      with:
        skip_existing: true
        password: ${{ secrets.PYPI_API_TOKEN }}

