name: pytest

on:
  push:
    branches: [ 'master' ]
  pull_request:
    branches: [ '*' ]

jobs:
  ci:
    runs-on: ${{ matrix.info.os }}
    strategy:
      matrix:
        info:
          - os: ubuntu-latest
            python: "3.9"
          - os: windows-latest
            python: "3.9"
          - os: macos-latest
            python: "3.10"
          - os: macos-10.15
            python: "3.9"
    name: ${{matrix.info.os}} ${{ matrix.info.python }}
    steps:
    - uses: actions/checkout@v3
      with:
          submodules: true
    - uses: actions/setup-python@v2
      name: Setup Python ${{ matrix.info.python }}
      with:
        python-version: ${{ matrix.info.python }}
    - uses: lukka/get-cmake@latest
    - name: Deps
      run: |
        python -m pip install --upgrade pip
        make requirements
    - name: Test
      shell: bash
      run: |
        ./ci-test.sh
        ./ci-cov.sh ${{ secrets.CODECOV_TOKEN }}
